print("Whats your name")
name=input()
print("Nice to meet you "+name)
print("how old are you")
age=input()
print("am Max Ai System say Max to start me up")
input()
print("Welcome Master "+name)
print("Thanks for trying The 1.2 version of Max Ai System Made by Shaquan Ceres")
print("lets start the demo test")
print("what year date and month you were born on")
form=input()
print("all the info you give "+name)
print("age: "+age)
print("date of birth: "+form)
print("to confirm this info is true say confirm info ok master "+name)
input()
print("info confirming")
from turtle import *
a=Turtle()
b=Screen()
a.color("red")
a.forward(100)
a.backward(100)
a.left(90)
a.forward(100)
a.right(90)
a.forward(100)
a.right(90)
a.forward(100)
print("demo test all done Master "+name)
print("Now starting up System loging you master "+name)
print("Welcome "+name)
print("hooking you up to our System loading")
c=Turtle()
d=Screen()
c.color("White")
c.forward(100)
c.backward(100)
c.left(90)
c.forward(100)
c.right(90)
c.forward(100)
c.right(90)
c.forward(100)
print("Max Ai System Ready, Starting up ")
print("Hi "+name)
input()
print("I am Max your Friendly AI Friend")
num1=input("Enter a number:")
num2=input("Enter another number:")
result=float(num1) * float(num2)
print(result)